name: DS-LegendaryCash
version: 1.0.0.28
main: com.darksoldier1404.dlc.LegendaryCash
api-version: 1.17
authors: [ DEAD_POOLIO_ ]
depend:
  - Essentials
commands:
  캐시:
    aliases: [ cash ]
  캐시상점:
    aliases: [ cashshop ]
