name: DP-LegendaryCash
version: 1.1.1.144
main: com.darksoldier1404.dlc.LegendaryCash
api-version: 1.12
authors: [ DEAD_POOLIO_ ]
depend:
  - DPP-Core
commands:
  캐시:
    aliases: [ cash ]
  캐시상점:
    aliases: [ cashshop ]
